language: perl
os:
  - linux
  # - osx

perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y libdevel-cover-perl
  - cpanm -n Devel::Cover::Report::Coveralls Test::Pod::Coverage Test::Pod::Spelling::CommonMistakes JSON::XS

install:
  - cpanm -v --installdeps --notest .

script:
  perl Makefile.PL && make && cover -test -report coveralls
